#!/bin/bash 
# NiCad localization wrapper for Unix-like systems
# J.R. Cordy, Queen's University, January 2011

# Revised July 2015

# Directory where NiCad has been installed
LIB=.

# Now run the appropriate version
$LIB/scripts/NiCadPair $LIB $*
